const fs = require('fs');
const path = require('path');

const summaries = {
  estj: {
    en: "A natural leader who gets things done efficiently.\nThey strictly follow rules and have the power to complete their assigned tasks to the end. They shine brighter in teams than alone, handling tasks accurately and quickly. However, they may sometimes push their ideas too strongly.\nThey are highly likely to naturally lead play with friends or become leaders in presentations or role-playing. They can grow into a trusted child by keeping rules and promises.\nPracticing listening to various opinions and having the courage to admit when they're wrong will make them an even better leader. Teaching them how to enjoy even in free play without rules will improve their balance.",
    id: "Pemimpin alami yang menyelesaikan sesuatu dengan efisien.\nMereka dengan ketat mengikuti aturan dan memiliki kekuatan untuk menyelesaikan tugas yang diberikan hingga akhir. Mereka bersinar lebih terang dalam tim daripada sendirian, menangani tugas secara akurat dan cepat. Namun, mereka terkadang memaksakan ide mereka terlalu kuat.\nMereka sangat mungkin untuk secara alami memimpin permainan dengan teman atau menjadi pemimpin dalam presentasi atau bermain peran. Mereka dapat tumbuh menjadi anak yang dipercaya dengan menepati aturan dan janji.\nBerlatih mendengarkan berbagai pendapat dan memiliki keberanian untuk mengakui kesalahan akan menjadikan mereka pemimpin yang lebih baik. Mengajari mereka cara menikmati bahkan dalam permainan bebas tanpa aturan akan meningkatkan keseimbangan mereka.",
    ms: "Pemimpin semula jadi yang melaksanakan tugasan dengan cekap.\nMereka mematuhi peraturan dengan ketat dan mempunyai kuasa untuk menyelesaikan tugas yang diberikan hingga akhir. Mereka bersinar lebih terang dalam pasukan berbanding sendirian, mengendalikan tugas dengan tepat dan pantas. Walau bagaimanapun, mereka kadang-kadang mungkin terlalu menekan idea mereka.\nMereka amat berkemungkinan untuk secara semula jadi memimpin permainan dengan rakan atau menjadi pemimpin dalam pembentangan atau main peranan. Mereka boleh membesar menjadi anak yang dipercayai dengan mematuhi peraturan dan janji.\nBerlatih mendengar pelbagai pendapat dan mempunyai keberanian untuk mengakui kesilapan akan menjadikan mereka pemimpin yang lebih baik. Mengajar mereka cara untuk berseronok walaupun dalam permainan bebas tanpa peraturan akan meningkatkan keseimbangan mereka.",
    th: "ผู้นำโดยธรรมชาติที่รับจัดการสิ่งต่างๆ ได้อย่างมีประสิทธิภาพ\nพวกเขาปฏิบัติตามกฎระเบียบอย่างเคร่งครัดและมีพลังที่จะทำงานที่ได้รับมอบหมายให้สำเร็จจนจบ พวกเขาจะเปล่งประกายเมื่ออยู่เป็นทีมมากกว่าอยู่เพียงลำพัง โดยสามารถจัดการงานได้อย่างแม่นยำและรวดเร็ว อย่างไรก็ตาม บางครั้งพวกเขาอาจผลักดันความคิดของตัวเองอย่างแรงกล้าเกินไป\nพวกเขามีแนวโน้มสูงที่จะเป็นผู้นำในการเล่นกับเพื่อนโดยธรรมชาติ หรือกลายเป็นผู้นำในการนำเสนองานหรือเล่นบทบาทสมมติ พวกเขาสามารถเติบโตเป็นเด็กที่ได้รับความไว้วางใจได้โดยการรักษากฎกติกาและคำมั่นสัญญา\nการฝึกให้รับฟังความคิดเห็นที่หลากหลายและมีความกล้าที่จะยอมรับเมื่อทำผิดพลาด จะช่วยให้พวกเขาเป็นผู้นำที่ดียิ่งขึ้น การสอนวิธีให้พวกเขาสนุกกับการเล่นอย่างอิสระโดยไม่มีกฎเกณฑ์ จะทำให้เกิดความสมดุลที่ดียิ่งขึ้น"
  },
  estp: {
    en: "Full of energy and loves to learn hands-on.\nHighly curious about new things and likes to learn by experiencing them physically. They have quick situational judgment and excellent immediate action, acting as a mood maker among friends.\nNot afraid of risks, they often try new games, but sometimes action precedes thought.\nThey are highly likely to stand out in activities that require immediate reactions like sports, exploration, performances, and games. Their momentary leadership in guiding friends shines, and their bold personality can make them stand out in presentations or on stage.\nAllowing them to have new experiences while teaching safety rules and risk prediction methods together will enable more balanced growth. Cultivating the habit of making a brief plan before an activity will develop both their action and judgment skills.",
    id: "Penuh energi dan suka belajar langsung.\nSangat ingin tahu tentang hal-hal baru dan suka belajar dengan mengalaminya secara fisik. Mereka memiliki penilaian situasional yang cepat dan tindakan segera yang sangat baik, bertindak sebagai pembuat suasana di antara teman-teman.\nTidak takut dengan risiko, mereka sering mencoba permainan baru, tetapi terkadang tindakan mendahului pemikiran.\nMereka sangat mungkin menonjol dalam aktivitas yang membutuhkan reaksi segera seperti olahraga, eksplorasi, pertunjukan, dan permainan. Kepemimpinan sesaat mereka dalam membimbing teman bersinar, dan kepribadian mereka yang berani dapat membuat mereka menonjol dalam presentasi atau di atas panggung.\nMembiarkan mereka memiliki pengalaman baru dengan mengajarkan aturan keselamatan dan metode prediksi risiko secara bersamaan akan memungkinkan pertumbuhan yang lebih seimbang. Menumbuhkan kebiasaan membuat rencana singkat sebelum suatu kegiatan akan mengembangkan kinerja dan keterampilan penilaian mereka.",
    ms: "Penuh dengan tenaga dan suka belajar secara hands-on.\nSangat berminat tentang perkara baharu dan suka belajar dengan mengalaminya secara fizikal. Mereka mempunyai pertimbangan situasi yang cepat dan tindakan segera yang cemerlang, bertindak sebagai penceria suasana di kalangan rakan-rakan.\nTidak takut dengan risiko, mereka sering mencuba permainan baharu, tetapi kadang-kadang tindakan mendahului pemikiran.\nMereka amat berkemungkinan akan menyerlah dalam aktiviti yang memerlukan reaksi segera seperti sukan, penerokaan, persembahan, dan permainan. Kepimpinan sementara mereka dalam membimbing rakan bersinar, dan keperibadian mereka yang berani boleh membuat mereka menyerlah dalam pembentangan atau di atas pentas.\nMembenarkan mereka mempunyai pengalaman baharu sambil mengajar peraturan keselamatan dan kaedah jangkaan risiko bersama-sama akan membolehkan tumbesaran yang lebih seimbang. Memupuk tabiat membuat rancangan ringkas sebelum aktiviti akan mengembangkan kemahiran pelaksanaan dan pertimbangan mereka.",
    th: "เปี่ยมไปด้วยพลังและรักการลงมือทำ\nอยากรู้อยากเห็นในสิ่งใหม่ๆ สูง และชอบเรียนรู้ด้วยการลงมือสัมผัสปฏิบัติจริง พวกเขาสามารถประเมินสถานการณ์และลงมือทำในทันทีได้อย่างยอดเยี่ยม มักสร้างบรรยากาศที่ดีให้กับกลุ่มเพื่อน\nไม่กลัวความเสี่ยงและมักลองเล่นเกมใหม่ๆ อยู่บ่อยครั้ง แต่บางครั้งก็อาจลงมือทำก่อนที่จะคิดทบทวน\nมีแนวโน้มสูงที่จะโดดเด่นในกิจกรรมที่ต้องการการตอบสนองทันที เช่น กีฬา การสำรวจ การแสดง และเกม ความเป็นผู้นำที่มักจะนำพากลุ่มเพื่อน และบุคลิกที่กล้าหาญจะทำให้พวกเขาโดดเด่นในการรายงานหน้าชั้นหรือบนเวที\nการเปิดโอกาสให้พวกเขาได้เรียนรู้ประสบการณ์ใหม่ๆ พร้อมกับการสอนเรื่องกฎความปลอดภัยและวิธีคาดการณ์ความเสี่ยง จะช่วยให้พวกเขาเติบโตได้อย่างสมดุล การปลูกฝังนิสัยวางแผนคร่าวๆ ก่อนเริ่มกิจกรรมจะช่วยพัฒนาทั้งทักษะการปฏิบัติและการตัดสินใจ"
  },
  esfj: {
    en: "Sweet and sociable; they are great at reading the room.\nFinds great joy in helping those around them. They are good at sensing changes in others' moods and creating a good atmosphere. Active in organizing gatherings or play and taking care of friends. However, sometimes they can exhaust themselves by being too conscious of others' expectations.\nThey are highly likely to become a 'central figure' in friendships, displaying excellent coordination skills in cooperative activities, gathering preparation, and joint projects. They can shine on stages where teamwork is important like presentations, choir, or plays.\nWhile utilizing their ability to help others, it is good to cultivate the habit of securing time and space for themselves. Teaching them the fact that 'it is difficult to satisfy everyone' will help them maintain healthier relationships.",
    id: "Manis dan supel; mereka pandai membaca suasana.\nMenemukan kegembiraan besar dalam membantu orang di sekitar mereka. Mereka pandai merasakan perubahan suasana hati orang lain dan menciptakan suasana yang baik. Aktif dalam mengatur pertemuan atau bermain dan merawat teman. Namun, terkadang mereka bisa kelelahan sendiri dengan terlalu sadar akan harapan orang lain.\nMereka sangat mungkin untuk menjadi 'figur sentral' dalam pertemanan, menampilkan keterampilan koordinasi yang sangat baik dalam aktivitas kooperatif, persiapan berkumpul, dan proyek bersama. Mereka dapat bersinar di panggung di mana kerja sama tim penting seperti presentasi, paduan suara, atau drama.\nSembari memanfaatkan kemampuan mereka untuk membantu orang lain, ada baiknya menumbuhkan kebiasaan meluangkan waktu dan ruang untuk diri mereka sendiri. Mengajari mereka fakta bahwa 'sulit untuk memuaskan semua orang' akan membantu mereka memelihara hubungan yang lebih sehat.",
    ms: "Manis dan sosial; mereka mahir membaca suasana bilik.\nMencari kegembiraan yang besar dalam membantu orang di sekeliling mereka. Mereka mahir merasakan perubahan mood orang lain dan mewujudkan suasana yang baik. Aktif dalam mengatur perjumpaan atau bermain dan menjaga rakan-rakan. Walau bagaimanapun, kadang-kadang mereka boleh memenatkan diri mereka dengan terlalu sedar akan harapan orang lain.\nMereka amat berkemungkinan untuk menjadi 'tokoh utama' dalam persahabatan, menampilkan kemahiran koordinasi yang cemerlang dalam aktiviti kerjasama, penyediaan perjumpaan dan projek bersama. Mereka boleh bersinar di pentas yang mana kerja berpasukan adalah penting seperti pembentangan, koir, atau drama.\nDi samping memanfaatkan keupayaan mereka untuk membantu orang lain, ia adalah baik untuk memupuk tabiat mendapatkan masa dan ruang untuk diri mereka sendiri. Mengajar mereka fakta bahawa 'adalah sukar untuk memuaskan hati semua orang' akan membantu mereka mengekalkan hubungan yang lebih sihat.",
    th: "น่ารักและเข้าสังคมเก่ง พวกเขาเก่งในการอ่านบรรยากาศรอบๆ\nมีความสุขมากในการได้ช่วยเหลือคนรอบข้าง พวกเขาเก่งในการสัมผัสถึงความเปลี่ยนแปลงทางอารมณ์ของผู้อื่นและสร้างบรรยากาศที่ดี กระตือรือร้นในการจัดระเบียบการรวมกลุ่มหรือการเล่น และดูแลเพื่อนๆ อย่างไรก็ตาม บางครั้งพวกเขาอาจทำให้ตัวเองเหนื่อยล้าเนื่องจากใส่ใจในความคาดหวังของคนอื่นมากเกินไป\nพวกเขามีแนวโน้มที่จะกลายเป็น 'บุคคลศูนย์กลาง' ในกลุ่มเพื่อน โดยแสดงทักษะประสานงานที่ยอดเยี่ยมในกิจกรรมที่ใช้ความร่วมมือ การเตรียมพร้อมสังสรรค์ และการทำงานกลุ่ม พวกเขาสามารถโดดเด่นในสถานที่ที่ความร่วมมือเป็นสิ่งสำคัญ เช่น การพรีเซนต์ การร้องประสานเสียง หรือการแสดงละคร\nแม้ว่าพวกเขาจะใช้ความสามารถในการช่วยเหลือผู้อื่นได้ดี แต่ก็ควรปลูกฝังนิสัยของการหาเวลาทบทวนและพื้นที่ส่วนตัวให้ตัวเอง การสอนพวกเขาให้รู้ว่า 'เป็นเรื่องยากที่จะทำให้ทุกคนพึงพอใจ' จะช่วยให้พวกเขารักษาสายสัมพันธ์ต่างๆ ได้ดียิ่งขึ้น"
  },
  esfp: {
    en: "Energetic, positive, and the life of the party who makes everyone smile.\nNot afraid of new people or new experiences. They are skilled at creating momentary joy and laughter, making people around them feel good. They adapt quickly to new games or activities and participate actively. However, preferring spontaneous choices over planning can sometimes result in disappointing outcomes due to lack of preparation.\nThey are highly likely to receive attention and stand at the center in events like festivals, performances, sports days, and camps. They transmit positive energy to their peers and often take the role of leading the atmosphere.\nWhile utilizing their tendency to pursue joy, cultivating the habit of preparation and concluding in important tasks will enable more stable growth. Practice in balancing spontaneity and planning is needed.",
    id: "Energik, positif, dan pusat pesta yang membuat semua orang tersenyum.\nTidak takut dengan orang baru atau pengalaman baru. Mereka ahli dalam menciptakan sukacita dan tawa sesaat, membuat orang di sekitar mereka merasa baik. Mereka beradaptasi dengan cepat pada permainan atau aktivitas baru dan berpartisipasi aktif. Namun, lebih menyukai pilihan spontan daripada perencanaan terkadang dapat menghasilkan hasil yang mengecewakan karena kurangnya persiapan.\nMereka sangat mungkin menerima perhatian dan berdiri di tengah dalam acara seperti festival, pertunjukan, hari olahraga, dan kemah. Mereka mentransmisikan energi positif kepada teman sebayanya dan sering mengambil peran sebagai pemimpin suasana.\nSembari memanfaatkan kecenderungan mereka untuk mengejar kegembiraan, menumbuhkan kebiasaan persiapan dan penyelesaian dalam tugas-tugas penting akan memungkinkan pertumbuhan yang lebih stabil. Latihan dalam menyeimbangkan kepraktisan spontan dan perencanaan diperlukan.",
    ms: "Bertenaga, positif, dan memeriahkan suasana yang membuatkan semua tersenyum.\nTidak takut dengan orang baharu atau pengalaman baharu. Mereka pakar dalam mencipta kegembiraan dan tawa seketika, membuat orang di sekeliling mereka berasa gembira. Mereka cepat menyesuaikan diri dengan permainan atau aktiviti baharu dan mengambil bahagian secara aktif. Walau bagaimanapun, lebih mengutamakan pilihan secara spontan daripada perancangan kadangkala boleh mengakibatkan hasil yang mengecewakan disebabkan kekurangan persiapan.\nMereka amat berkemungkinan akan mendapat perhatian dan berada di tengah-tengah acara seperti festival, persembahan, hari sukan dan perkhemahan. Mereka menyalurkan tenaga positif kepada rakan sebaya dan sering mengambil peranan mengetuai suasana.\nSambil menonjolkan kecenderungan mereka untuk mengejar kegembiraan, memupuk tabiat penyediaan dan kesimpulan dalam tugas-tugas penting akan membolehkan tumbesaran yang lebih stabil. Latihan mengimbangi perkara spontan dan perancangan diperlukan.",
    th: "ร่าเริง แจ่มใส และเป็นสีสันของงานที่ทำให้ทุกคนยิ้ม\nไม่กลัวผู้คนใหม่ๆ หรือประสบการณ์ใหม่ๆ เขาเก่งในการสร้างความสนุกสนานและเสียงหัวเราะในโมเมนต์นั้นๆ ทำให้คนรอบข้างรู้สึกดี ปรับตัวเข้ากับเกมหรือกิจกรรมใหม่ๆ ได้อย่างรวดเร็วและมีส่วนร่วมอย่างกระตือรือร้น อย่างไรก็ตาม การชอบเลือกตัดสินใจในทันทีมากกว่าการวางแผน อาจส่งผลลัพธ์ที่น่าผิดหวังในบางครั้งเนื่องจากขาดการเตรียมพร้อม\nพวกเขามีแนวโน้มที่จะได้รับความสนใจและเป็นจุดศูนย์กลางในงานต่างๆ เช่น เทศกาล การแสดง วันแข่งกีฬา และค่ายกิจกรรม พวกเขาอาจส่งมอบพลังงานบวกให้กับเพื่อนฝูง และมักจะรับบทบาทในการสร้างบรรยากาศอยู่เสมอ\nในขณะที่ดึงเอาข้อดีทางการชอบสร้างความสุขของพวกเขาออกมาใช้ การปลูกฝังนิสัยการเตรียมตัวและการสร้างบทสรุปในสิ่งสำคัญจะช่วยให้พวกเขาเติบโตได้อย่างมั่นคงมากยิ่งขึ้น พวกเขาต้องฝึกฝนการสร้างสมดุลระหว่างความฉับไวและการวางแผน"
  },
  entj: {
    en: "Highly driven to set their own goals and achieve them.\nEfficiently plans and drives things forward. Shows no hesitation in finding center and making decisions in any situation. Highly competitive and enthusiastic about taking on difficult challenges. However, sometimes they can become impatient, unable to wait for the pace of those around them.\nThey are highly likely to achieve results in group activities or projects requiring leadership. Will grow significantly in goal-oriented environments like sports, debates, or startup camps.\nAdding 'listening to others' opinions' and 'pacing' to their fast driving force will earn them greater trust. Experiencing failure and developing the flexibility to cope will mature their leadership.",
    id: "Sangat terdorong untuk menetapkan dan mencapai tujuan mereka sendiri.\nSecara efisien merencanakan dan mendorong berbagai hal ke depan. Tidak membenarkan keraguan dalam menemukan pusat dan membuat keputusan dalam situasi apa pun. Sangat kompetitif dan antusias mengambil tantangan sulit. Namun, terkadang mereka menjadi tidak sabar, tidak bisa menunggu langkah orang di sekitar mereka.\nMereka sangat mungkin mencapai hasil yang baik dalam aktivitas kelompok atau proyek yang membutuhkan kepemimpinan. Akan tumbuh secara signifikan dalam lingkungan yang berorientasi pada tujuan seperti olahraga, debat, atau kamp startup.\nMenambahkan 'mendengarkan pendapat orang lain' dan 'mengatur langkah' pada daya penggerak cepat mereka, akan membuat mereka dipercaya. Mengalami kegagalan dan mengembangkan fleksibilitas untuk mengatasi akan mendewasakan kepemimpinan mereka.",
    ms: "Sangat bersemangat untuk menetapkan matlamat mereka sendiri dan mencapainya.\nMerancang dan memacu perkara ke hadapan dengan cekap. Mempamerkan tiada keraguan dalam mencari pertengahan dan membuat keputusan dalam apa jua keadaan. Sangat berjiwa pesaing antusias terhadap sesuatu cabaran. Namun, kadang-kadang mereka boleh menjadi tidak sabar, tidak mampu menunggu rentak orang di sekeliling mereka.\nMereka berkemungkinan besar akan mencapai keputusan yang cemerlang dalam aktiviti kumpulan atau projek yang memerlukan daya kepimpinan. Akan berkembang dengan pesat dalam persekitaran yang berorientasikan matlamat seperti sukan, debat, atau perkhemahan syarikat baharu.\nMenambah kualiti 'mendengar pendapat orang lain' dan 'rentak' kepada daya pergerakan pantas mereka, akan menjauhkan mereka kepada lebih ramai pengikut. Mengalami kegagalan dan mengasuh ketahanan mendemonstrasi akan mematangkan kepimpinan mereka.",
    th: "มีความมุ่งมั่นตั้งเป้าหมายและขับเคลื่อนสูง\nวางแผนและผลักดันสิ่งต่างๆ ไปข้างหน้าอย่างมีประสิทธิภาพ ไม่มีความลังเลที่จะหาศูนย์กลางและเปิดการตัดสินใจในสถานการณ์ใดๆ ก็ตาม มีความชอบการแข่งขันสูงและกระตือรือร้นที่จะเผชิญรับความท้าทายยากๆ อย่างไรก็ตาม บางครั้งพวกเขาอาจเกิดความกระวนกระวายหรือไม่มีความอดทนรอที่จะเดินไปพร้อมกับคนอื่นๆรอบข้าง\nพวกเขามีแนวโน้มที่จะบรรลุผลลัพธ์ในกิจกรรมกลุ่มหรือโปรเจกต์ที่ต้องใช้ความเป็นผู้นำ พวกเขาจะเติบโตอย่างก้าวกระโดดในสภาพแวดล้อมที่มุ่งเน้นเป้าหมาย เช่น กีฬา งานแข่งขันโต้แย้ง หรือแคมป์พัฒนากิจกรรม\nการเพิ่มทักษะ 'การรับฟังความคิดเห็นของผู้อื่น' และ 'การกะจังหวะ' เข้ากับพลังขับเคลื่อนที่รวดเร็วของพวกเขา จะช่วยให้ได้รับความไว้วางใจมากขึ้น การสัมผัสถึงความล้มเหลวและพัฒนาความยืดหยุ่นในการรับมือจะทำให้ความเป็นผู้นำของพวกเขาเป็นผู้ใหญ่ขึ้น"
  },
  entp: {
    en: "Overflowing with ideas, they have to try things out themselves to be satisfied.\nHighly curious and looks at problems from various perspectives. Excels in debates and presentations due to their eloquence and quick thinking. However, preferring spontaneity over planning can result in weak follow-through.\nThey are highly likely to be active in invention contests, creativity camps, and debate competitions. Will entertain friends by creating new games or modifying rules.\nTo realize their abundant ideas, it is important to cultivate the 'habit of finishing what they start'. Guiding them to balance spontaneity and planning will increase their sense of accomplishment.",
    id: "Melimpah dengan ide, harus mencobanya sendiri agar puas.\nSangat ingin tahu dan melihat masalah dari berbagai perspektif. Unggul dalam debat dan presentasi karena kefasihan dan pemikiran cepat mereka. Namun, lebih menyukai langkah spontan daripada perencanaan dapat mengakibatkan tindak lanjut yang lemah.\nMereka mungkin sangat aktif dalam kompetisi penemuan, kamp kreativitas, dan kompetisi debat. Akan menghibur teman-teman dengan membuat permainan baru atau memodifikasi aturan.\nUntuk merealisasikan ide mereka yang melimpah, penting untuk menumbuhkan 'kebiasaan menyelesaikan apa yang mereka mulai'. Membimbing mereka untuk menyeimbangkan spontanitas dan perencanaan akan membuktikan rasa pencapaian mereka.",
    ms: "Berlimpah dengan idea, mereka perlu mencuba sendiri.\nSangat ingin tahu dan melihat masalah dari pelbagai perspektif. Cemerlang dalam debat dan pembentangan kerana kepetahan dan daya pemikiran pantas mereka. Walau bagaimanapun, mempunyai rasa spontan berbanding perancangan mungkin mengakibatkan susulan yang lemah.\nMereka mungkin sangat aktif dalam pertandingan ciptaan, kem kreativiti, dan pertandingan perbahasan. Akan menghiburkan rakan-rakan dengan mencipta permainan baharu atau mengubah suai spesifikasi permainan semasa.\nUntuk merealisasikan idea mereka yang banyak, ini adalah penting untuk memupuk 'kebiasaan menyelesaikan apa yang mereka mula'. Membimbing mereka untuk seimbangkan masa persekitaran akan membuktikan rasa kepuasan mereka.",
    th: "เต็มไปด้วยไอเดียและต้องลองทำเองถึงจะพึงพอใจ\nมีความอยากรู้อยากเห็นสูงและมองปัญหาจากหลายมุมมอง มีความโดดเด่นในการโต้แย้งและการนำเสนอเนื่องจากความเฉียบแหลมและการคิดที่รวดเร็วของตน แต่การชอบความฉับไวมากกว่าการวางแผนอาจทำให้ทำสิ่งต่างๆ ไม่ต่อเนื่องจนจบกระบวนการ\nมีแนวโน้มสูงที่จะกระตือรือร้นในการเข้าร่วมในงานประกวดนวัตกรรม ค่ายเสริมสร้างคามคิดสร้างสรรค์ และการแข่งขันโต้แย้ง พวกเขาจะสร้างความบันเทิงให้เพื่อนๆ ด้วยการคิดเกมใหม่ๆ หรือดัดแปลงกฎเกณฑ์การละเล่นเดิมๆ\nเพื่อทำให้ไอเดียอันมากมายของพวกเขาเป็นจริง สิ่งที่สำคัญคือการปลูกฝัง 'นิสัยในการทำให้สิ่งที่เริ่มไว้เสร็จสมบูรณ์' การแนะนำพวกเขาให้สร้างสมดุลระหว่างความฉับพลันและการวางแผนจะช่วยเพิ่มความรู้สึกถึงความสำเร็จได้"
  },
  enfj: {
    en: "Caring and always wants everyone to get along and be happy.\nFinds meaning in relationships. Good at discovering others' strengths and encouraging them. Has a warm heart, approaching and helping friends in need first. However, they can take on too much of others' problems.\nThey will stand out in volunteer activities, leadership camps, and cooperative projects. Highly likely to act as a 'sturdy pillar' in friendships.\nThey must be taught how to take care of their own emotions as much as they help others. Maintaining healthy relationships while keeping 'the boundaries of my share' will make them a good leader for a long time.",
    id: "Peduli dan selalu ingin semua orang akur dan bahagia.\nMenemukan makna dalam hubungan. Pandai menemukan kekuatan orang lain dan mendorong mereka. Memerlukan hati yang hangat, mendekati dan membantu teman yang membutuhkan terlebih dahulu. Namun, mereka dapat mengambil terlalu banyak masa lalu dari masalah orang lain.\nMereka akan sangat menonjol dalam kegiatan kerelawanan, kamp kepemimpinan, dan proyek kerja sama. Kemungkinan besar bertindak sebagai 'pilar kokoh' di pertemanan.\nMereka harus diajarkan bagaimana merawat emosi mereka sendiri sebanyak mereka membantu orang lain. Mempertahankan hubungan yang sehat sambil menahan 'batas bagian mereka' akan membuat mereka pemimpin yang baik untuk waktu yang lama.",
    ms: "Penyayang dan sentiasa mahukan semua orang harmoni dan gembira.\nMencari erti sebenar dalam perhubungan sesama manusia. Pakar dalam menjumpai kekuatan orang lain dan mengalakkan mereka. Mempunyai hati yang mesra, menghampiri dan membantu rakan yang dalam kesusahan dahulu. Namun begitu, mereka boleh mencampurkan pada terlalu banyak masalah orang disekeliling mereka.\nMereka akan lebih menyerlah dalam aktiviti sukarelawan, kem kepimpinan dan projek kerjasama. Mudah untuk bertindak sebagai seorang 'tungku kukuh' di antara kawan-kawan.\nMereka mesti diajar cara menjaga emosi mereka sendiri dan membandingkan pertolongannya dengan yang lainnya. Mengekalkan perhubungan peribadi sementara menyimpan 'had pembahagian saya' akan mematangkn mereka untuk menjadi sorang pewira.",
    th: "ห่วงใยและอยากให้ทุกคนเข้ากันได้และมีความสุขเสมอ\nค้นพบความหมายที่ซ่อนอยู่ในสายใยความสัมพันธ์ มีทักษะในการค้นหาจุดเด่นของผู้อื่นและสนับสนุนพวกเขา มีจิตใจอบอุ่น เป็นคนแรกๆ ที่จะเข้าหาและช่วยเหลือเพื่อนที่กำลังลำบาก อย่างไรก็ตาม บางครั้งพวกเขาก็อาจแบกรับปัญหาของคนอื่นมากเกินไป\nพวกเขาจะโดดเด่นในกิจกรรมอาสาสมัคร ค่ายผู้นำ และโปรเจกต์ที่ต้องอาศัยความร่วมมือ มีความเป็นไปได้สูงที่จะทำหน้าที่เป็น 'เสาหลักที่มั่นคง' ให้กับกลุ่มเพื่อนๆ\nสิ่งสำคัญคือต้องสอนวิธีดูแลความรู้สึกอารมณ์ของตนเองพอๆ กับที่พวกเขาช่วยเหลือผู้อื่น การรักษาทักษะทางความสัมพันธ์ที่ดีต่อสุขภาพพร้อมกับตระหนักไว้ใน 'ขอบเขตหน้าที่ของฉัน' จะช่วยให้พวกเขาเป็นผู้นำที่ดีในระยะยาว"
  },
  enfp: {
    en: "Warm-hearted and bursting with curiosity for new things.\nCreative and has rich imagination. Finds joyful ideas and adventures, making their surroundings lively. Not afraid of change and challenges. However, it can be difficult to focus on one thing for a long time.\nThey are highly likely to lead new attempts in various activities and become a mood maker in clubs or gatherings.\nCultivating the habit of completing goals to the end while maintaining interest will greatly expand their potential. Practice in connecting ideas with execution plans is needed.",
    id: "Berhati hangat dan penuh rasa ingin tahu terhadap hal-hal baru.\nKreatif dan memiliki imajinasi yang kaya. Menemukan ide yang menyenangkan dan petualangan, membuat lingkungan mereka hidup. Tidak takut pada perubahan dan tantangan. Namun, dapat sulit untuk fokus pada satu hal untuk waktu yang lama.\nMereka sangat mungkin memimpin percobaan baru dalam berbagai aktivitas dan menjadi pembuat suasana di klub atau pertemuan.\nMenumbuhkembangkan kebiasaan menyelesaikan sasaran sampai akhir sambil mempertahankan minat, akan sangat mengembangkan potensi mereka. Latihan dalam menghubungkan ide dengan rencana eksekusi diperlukan.",
    ms: "Baik hati dan penuh dengan rasa ingin tahu terhadap perkara baharu.\nKreatif dan mempunyai imaginasi yang luas. Menjumpai idea yang memberi kebahagiaan dan mengembara dalam menginang hal di sekeliling mereka. Tidak takut perubahan dan tantangan. Walau bagaimanapun, ia mungkin sukar untuk memberikan tumpuan penuh kepada sesuatu sasaran.\nMereka mudah untuk mengambil bahagian dalam pelbagai percubaan aktivti baru serta sangat berkemampuan menjadi punca penambah persekitaran baharu di mana kelab atau perhimpuan.\nDengan mengasah sikap menyempurnakan sasaran sehingga akhir juga mempertahankan keminatan bakal menambahkan potensi mereka. Menyesuaikan idea di alam maya serta di dunia juga mendemonstrasikan keupayaan penuh mereka.",
    th: "มีจิตใจที่อบอุ่นและเต็มไปด้วยความอยากรู้อยากเห็นในสิ่งใหม่ๆ\nมีความคิดสร้างสรรค์และจินตนาการอันล้ำเลิศ เป็นพวกกระตือรือร้นและมักค้นพบไอเดียสนุกๆ แสวงหาการผจญภัย ทำให้บรรยากาศรอบตัวมีชีวิตชีวา ไม่เกรงกลัวความเปลี่ยนแปลงและความท้าทาย แต่อาจมีปัญหาในการจดจ่ออยู่กับสิ่งใดสิ่งหนึ่งเป็นเวลานาน\nพวกเขามีแนวโน้มที่จะเป็นผู้นำในการลองริเริ่มสิ่งใหม่ๆ ในกิจกรรมต่างๆ และยังเป็นหัวหอกสีสันให้กับกลุ่มชุมชนหรือชมรม\nการปลูกฝังอุปนิสัยในการเป้าหมายให้เสร็จลุล่วงไปจนจบพร้อมๆ ไปกับการรักษาความสนใจของตัวเองไว้ จะช่วยเพิ่มศักยภาพของพวกเขาได้อย่างมาก ควรฝึกการเชื่อมโยงไอเดียเข้ากับแผนการลงมือทำ"
  },
  istj: {
    en: "Highly responsible and strictly follows rules and order.\nValues stability and order. Has the power to plan and proceed step by step. Completes assigned tasks to the end, earning the trust of those around them. However, they can find changes burdensome.\nThey will show strengths in learning, sports with rules, and long-term projects. Consistent effort is highly likely to lead to results.\nPracticing taking small challenges in new environments while utilizing their stable strengths can give them broader possibilities.",
    id: "Sangat bertanggung jawab dan sangat patuh pada aturan dan ketertiban.\nMenghargai stabilitas dan ketertiban. Memiliki kekuatan untuk merencanakan dan melanjutkan proses selangkah demi selangkah. Menyelesaikan tugas yang diberikan hingga akhir, mendapatkan kepercayaan orang di sekitar mereka. Namun, mereka bisa mendapati perubahan itu membebani.\nMereka akan menunjukkan kekuatan dalam pembelajaran, olahraga dengan peraturan, dan proyek jangka panjang. Usaha yang konsisten kemungkinan akan mengarah ke hasil maksimal.\nBerlatih mengambil tantangan perlahan di lingkungan mana pun, dengan memanfaatkan kekuatan alami mereka yang tenang, akan menjauhkan mereka untuk tantangan yang lebih baik.",
    ms: "Amanah dan mengikuti peraturan serta ketertiban dengan teliti.\nMenghargai keharmonian stabiliti sosial serta tertib peraturan. Mengarahkan kuasa untuk merangcang perletakan pelan mereka. Menunaikan tuntutan yang ditugaskan kepada mereka sampai di akhir, membina persekitaran keahlian terpecayakan. Namun, menukar peraturan mendemonstrasikan yang itu sunguh membebanan.\nMereka akan memaparkan keunggulan yang menyerlah di dalam pembelajaran bertema sukan berdisplin juga tugasan secara melanjut. Tindakan usaha gigih akan membawa padah pencapain maksimum.\nMelatih amalan mengambil risiko yang perlapan-lapan di persekitaran mana-manapun, membukakan peluang untuk mengasah keberanian serta memperkuatkan mereka kepada potensi pencapaian berlipat kali ganda.",
    th: "มีความรับผิดชอบสูงและปฏิบัติตามกฎเกณฑ์ความเป็นระเบียบเรียบร้อย\nให้คุณค่ากับความมั่นคงและความเป็นระเบียบ มีศักยภาพในการวางแผนและดำเนินการไปทีละขั้นตอน พวกเขาทำทิ้งไว้ไม่ได้ และมักจะทำงานที่ได้รับมอบหมายจนสำเร็จ ทำให้ได้รับความไว้วางใจจากคนรอบตัว แต่พวกเขาอาจมองว่าการเปลี่ยนแปลงเป็นภาระ\nพวกเขาจะแสดงความโดดเด่นในด้านวิชาการ กีฬาที่ต้องใช้ระเบียบกติกา และโปรเจกต์ระยะยาว ความพยายามอย่างสม่ำเสมอมีแนวโน้มที่จะนำไปสู่ผลลัพธ์ที่ดีเสมอ\nการฝึกฝนรับความท้าทายเล็กๆ น้อยๆ ในสภาพแวดล้อมใหม่ๆ ในขณะที่ใช้ข้อดีด้านความมั่นคงในตัวเอง จะสามารถช่วยเพิ่มฐานความสามารถของพวกเขาให้ไปได้ไกลยิ่งขึ้น"
  },
  istp: {
    en: "Quiet on the outside, but highly logical and analytical on the inside.\nAdapts quickly to situations. Has excellent dexterity and observation skills, and likes learning by actually doing things. However, they may have low interest in long-term plans.\nThey will stand out in 'body-learning activities' like crafting, experiments, and sports. Calmly finds solutions in crisis situations.\nWhile utilizing their spontaneous strengths, cultivating the habit of taking on tasks with a long breath will broaden their scope of growth.",
    id: "Tenang di luar, tetapi sangat logis dan analitis di dalam.\nBeradaptasi dengan cepat terhadap situasi. Memiliki keterampilan ketangkasan dan observasi yang sangat baik, dan suka belajar dengan benar-benar melakukan sesuatu. Namun, mereka mungkin memiliki minat yang rendah terhadap rencana jangka panjang.\nMereka akan sangat bersinar dalam 'aktivitas pembelajaran tubuh' yang berbasis perakitan, eksperimen, dan olahraga. Menemukan solusi dalam situasi tertekan.\nSambil memanfaatkan kekuatan berprinsip mereka, menanamkan kebiasaan mengambil tugas panjang perlahan akan meluaskan pencapain dan perkembangan mereka.",
    ms: "Pendiam dari luar, tetapi sangat logik dan analitikal di dalam.\nMenyesuaikan ke pelbagai situasi demgan lebih pantas. Memaparkan ketangkasan dan observasi tinggi dari kelaziman, serta amat menyukai pembelajaran jenis fizikal secara praktikal. Namun, boleh dikaitakan dengan minat pendahuluan yang singkat bagi pelan masa depan melanjut.\nMereka akan lebih menyerlah secara semualahjadi dalam aktiviti bertemankan 'pembelajaran keanggotan tubuh badan' seperti kesenian kraf, pelbagai eksperimen uji kaji, serta aktiviti sukan. Secara menenangkan, menyisat jalan penyelesaian untuk kesusahan yang maut.\nSementara mengambil kesempatan bagi naluri pontan diri mereka, melatih kebiasaan untuk sentiasa memanjangkan masa pada tugasan-tugasan ini akan menyerlakan pontensi pencapaian.",
    th: "เงียบขรึมภายนอก แต่มีตรรกะและการวิเคราะห์สูงภายในอยู่\nปรับตัวเข้ากับสถานการณ์ได้อย่างรวดเร็ว มีทักษะความคล่องแคล่วและการสังเกตที่ยอดเยี่ยม และชอบเรียนรู้ด้วยการลงมือทำจริงๆ อย่างไรก็ตาม พวกเขาอาจมีความสนใจในแผนการระยะยาวค่อนข้างต่ำ\nพวกเขาจะโดดเด่นใน 'กิจกรรมการเรียนรู้ทางร่างกาย' เช่น งานประดิษฐ์ การทดลอง และกีฬา สามารถค้นหาวิธีแก้ปัญหาได้อย่างใจเย็นในสถานการณ์วิกฤต\nแม้ว่าจะใช้จุดแข็งในด้านความฉับพลันของตนเอง การปลูกฝังนิสัยเพื่อพัฒนาความกล้าใจนิ่งในการจัดการกับงานต่างๆ นั้นจะช่วยขยายขอบเขตการเติบโตต่อไปให้พวกเขาได้อย่างแน่นอน"
  },
  isfj: {
    en: "A deeply considerate child who shows warmth through actions rather than words.\nLikes to help people around them. Carefully takes care of others and quietly finishes assigned tasks to the end. However, putting others before their own emotions can exhaust them.\nThey will become a trusted member in caregiving, volunteering, and group assignments.\nGuiding them to have time and hobbies for themselves will allow them to maintain their energy and help others for a long time.",
    id: "Anak yang sangat penuh pertimbangan yang menunjukkan kehangatan melalui tindakan.\nSuka membantu orang di sekitar mereka. Sangat berhati-hati merawat orang lain dan perlahan demi perlahan menyelesaikan tugas yang ada. Namun, mendahulukan pihak kedua sebelum kepentingan sendiri sering membuat terkuburnya harapan diri mereka sendiri.\nMereka akan menjadi teman atau bagian terpercaya dalam merawat, keikhlasan bekerja dan tugas-tugas tim kolektif.\nMembimbing mereka untuk memiliki waktu tersendiri serta waktu menekuni hobi demi mempertahankan kebahagian mereka dapat menjamin pertemanan sehat berumur panjang.",
    ms: "Kanak-kanak yang prihatin yang menunjukkan kemesraan melalui tindakan.\nKanak-kanak mulia dan bertimbang rasa yang memartabatkan kemesraan pertolongan laku perbuatan menandingi ungkapan lidah.\nSuka untuk membantu persekitaran mereka. Berhenti rehat merawat orang lain lalu menerap kembali dalam tugasan mereka hingga kesudahan. Namun, memfokuskan kepada kehendak mereka atas diri akan memulaukan rasa keletihan emosi yang meluap luap.\nMereka bakal menjadi sebahagi yang dipercayakan dalam hal penderian, penyukarelaan, juga persatuan tugasan berkumpulan.\nMemandu mereka kearah menghargai percutian kendirian dalam menekuni riadah dapat melambungkan pengkekalan tenaga yang mana mencorong mereka ke masa dapan bertema pertolongan sekeliling buat selamanya.",
    th: "เป็นเด็กที่มีความเห็นอกเห็นใจผู้อื่นอย่างลึกซึ้ง แสดงความอบอุ่นผ่านการกระทำมากกว่าคำพูด\nชอบช่วยเหลือคนรอบข้าง ดูแลผู้อื่นอย่างระมัดระวังและทำงานที่ได้รับมอบหมายจนสำเร็จอย่างเงียบๆ อย่างไรก็ตาม การให้ความสำคัญกับผู้อื่นมากกว่าความรู้สึกของตนเองอาจทำให้พวกเขาเหนื่อยล้าเกินไป\nพวกเขาจะกลายเป็นสมาชิกที่ได้รับความไว้วางใจในการดูแล งานอาสาสมัคร และงานกลุ่ม\nการจัดเตรียมและจัดสรรช่วงเวลาพักหรือเวลาว่างเพื่อสนับสนุนงานอดิเรกในสิ่งที่พวกเขาชื่นชอบจะช่วยให้พวกเขารักษาระดับพลังงานได้และทำให้พวกเขาสามารถเป็นช่วยเหลือผู้อื่นได้อย่างมีความสุข"
  },
  isfp: {
    en: "Highly perceptive and quietly expresses their own unique sense of beauty.\nImmerses in sensory activities like nature, art, and music. However, strongly asserting their opinions can be burdensome.\nThey are highly likely to show talent in creative fields like art, music, design, and writing.\nLearning various ways of self-expression will allow them to share their heart with more people.",
    id: "Sangat tanggap dan secara diam-diam mengekspresikan rasa keindahan yang unik.\nTenggelam dalam segala kegiatan berekspresi seperti seni, musik dan alam raya. Namun, sulit menegaskan pendapat mereka di hadapan orang lain atas pemikiran tersebut.\nMereka sangat berbakat menjadi bagian yang berhubungan dalam karya kreatif seperti desain, penceritaan dan juga seni musik.\nMengajari cara lain berekspresi secara merdeka akan perlahan mengangkat pandangan keindahan mereka serta menjebatani relasi dengan semua temannya dalam masa sekolah mereka.",
    ms: "Perseptif tinggi dan menyatakan rasa kecantikannya yang unik dengan tenang.\nMemabuki alam persepsi peribadi tersendiri bersandarkan fitrah, karya, atau lagu merdu. Walau begitu, menindih pendapat kepada khalayak awam bisa ditangap sesuatu yang merimaskan untuk mereka.\nSungguh mungkin mendedahkan ketajaman pontensinya pada pelbagai penglibatan kreatif saperti kesenian, irama muzik, rekaan visual pelan pembinaan atau pertilasan sastera moden.\nMengajarkan pemaparan pemikiran tersendiri mendedahkan pertuturan hati mesra ke dunia di kelilingi.",
    th: "มีความสามารถในการรับรู้สูงและมักแสดงออกถึงความรู้สึกทางความงามที่เป็นเอกลักษณ์ของตนเอง\nดำดิ่งและดื่มด่ำไปกับกิจกรรมที่ใช้ประสาทสัมผัส เช่น ธรรมชาติ ศิลปะ และดนตรี อย่างไรก็ตาม การแสดงความคิดเห็นอย่างหนักแน่นอาจเริ่มทำให้เป็นภาระในใจ\nมีแนวโน้มสูงที่จะแสดงพรสวรรค์ในสาขาสร้างสรรค์ เช่น ศิลปะ ดนตรี การออกแบบ และการเขียน\nการเรียนรู้วิธีแสดงอารมณ์ออกในหลากหลายวิธีจะช่วยให้สื่อความรู้สึกจากใจของตนเองกับคนรอบข้างได้อย่างดี"
  },
  intj: {
    en: "A deep thinker who values self-satisfaction over external validation.\nIndependently advances toward goals. Strong in logic and analysis, excelling at finding efficient methods. However, perfectionism can pressure them.\nThey will show strengths in science, strategy games, and research projects.\nIncreasing flexibility in the process of achieving goals and expanding collaborative experiences with others will broaden their perspective.",
    id: "Pemikir mendalam yang menghargai kepuasan diri di atas pengakuan eksternal.\nMaju terus secara mandiri untuk tujuan dan sasaran awal. Memiliki kepiwaian tajam untuk analisa analitik secara tajam mencari pelbagai penyelesaian secara rapih. Tapi, terkadang tekanan perfeksionis meradang.\nMuncul paling atas jika menyangkut eksperimen proyek, permainan intelek yang memerlukan penyusunan strategik dan kajian berfikir.\nPeningkatan kecekapan akan tercapai tatkala bisa memahami relasi rekan sesama dan melepaskan kelonggaran keluwesan kerja dalam penyelesaian yang memerlukan pencapaian rapi dari pelbagai tangan teman kelompoknya.",
    ms: "Pemikir yang sangat menimbangkan kepuasan diri mengatasi pengiktirafan luaran.\nMaju menuju objektif bersandarkan matlamat mutlak kendiri. Sektar logikalnya seerta analitikal menonjol demi menjejaki gaya berkesan mencapai kejayaan optimum bersertakan kecermelangan unggul. Kesempurnan tegar kekadang menggugut.\nAkan memperlihatkan keberhasilan mantap dalan penyangkuan kajian makmal saintifik, permainan cerdik menguji kewibawaan dan susun perancangan tugasan ilmiah.\nMengamalkam kelongaran kerja secara bertahap demi melebarkan empayar pamerhatian kolaborasi kemasyarkatan bagi keupayaan berterusan berjangka panjang.",
    th: "นักคิดลึกซึ้งผู้ที่ให้คุณค่ากับความพึงพอใจในตนเองมากกว่าการยกย่องจากภายนอก\nมุ่งมั่นก้าวไปสู่เป้าหมายด้วยตัวเอง มีความแข็งแกร่งในด้านตรรกะและการวิเคราะห์ เชี่ยวชาญในการหาวิธีการที่มีประสิทธิภาพที่ดีที่สุดแต่ความสมบูรณ์แบบอาจสร้างแรงกดดันให้กับพวกเขาเองได้\nพวกเขาจะแสดงความโดดเด่นในสาขาวิทยาศาสตร์ เกมเชิงกลยุทธ์ และโครงงานวิจัย\nการเพิ่มความยืดหยุ่นในกระบวนการทำงานเพื่อไปสู่เป้าหมาย และการแสวงหาการเปิดรับประสบการณ์ร่วมกับผู้อื่น จะช่วยเปิดวิสัยทัศน์ของพวกเขาให้กว้างไกลและลึกมากขึ้น"
  },
  intp: {
    en: "Full of curiosity, they explore the world in their own unique way.\nEnjoys deep exploration and analysis. Immerses in understanding new concepts and principles. However, they can often stay in thoughts rather than execution.\nThey can achieve excellent results in knowledge exploration fields like science, math, programming, and invention.\nTranslating thoughts into small experiments and projects will increase their sense of accomplishment.",
    id: "Penuh rasa ingin tahu, mereka menjelajahi dunia dengan cara yang menarik.\nSangat menikmati eksplorasi dan penggalian analitik dalam wawasan kajian tersendiri. Namun terkadang, pemikiran akan menghanyutkan kelembamam pengeksekusian nyata di alam luar.\nMereka mungkin bakal sukses cemerlang untuk bidang pelajaran yang memerlukan eksprimental dalam seperti permesinan, pengetahuan alam, matematis saintis dan pemprogramman.\nMenterjemahkan kajian mereka walau kedalam wujud sekecil apapun akan membuktikan pencermelangan keberhasilan pemahaman bagi sang anak.",
    ms: "Penuh rasa ingin tahu, mereka meneroka dunia dengan cara yang unik.\nMenikmati pengalaman pencerobohan sedalam mungkin sambil mencari nilai analitikal penyiasatan. Tengelam dalam menzahirankan pengatahuan dalaman mendalam berpanjangan. Tapi agak sepi dalam dunia menzahirankan lakonan impian alam kenyataan.\nMencapai tahap maksima pencapaian sekiranya di dalam arena penyiasatan bersandarkan pengetahuan baru saintifik, teori perhutangann angka, sains pembacaan mahupun pengkaryaan baru cipta.\nPengukir minda kepada bentuk laksanaan walaupun saiz yang minima bakal menjadikan pengakhiran penzahiran rasa penyempurnan kepada impian sang anak.",
    th: "เต็มไปด้วยความอยากรู้อยากเห็นในแบบของตนเอง\nเพลิดเพลินกับการผจญภัยสำรวจและวิเคราะห์อย่างลึกซึ้ง หมกมุ่นกับการทำความเข้าใจแนวคิดและหลักการใหม่ๆ อย่างไรก็ตาม พวกเขามักจะจมอยู่กับความคิดมากกว่าการลงมือปฏิบัติจริง\nพวกเขาสามารถประสบความสำเร็จอย่างยอดเยี่ยมในสาขาการสำรวจความรู้ เช่น วิทยาศาสตร์ คณิตศาสตร์ การเขียนโปรแกรม และนวัตกรรมสิ่งประดิษฐ์\nการแปลงความคิดให้เป็นการทดลองและโปรเจกต์ขนาดเล็กๆ จะช่วยเพิ่มความรู้สึกถึงความสำเร็จได้มากขึ้นในตัวของนักค้นคว้าตัวน้อยนี้"
  },
  infj: {
    en: "Highly imaginative and deeply sensitive to the emotions of others.\nHas insight into people's hearts and the meaning of situations. However, they can easily tire without enough alone time.\nThey are highly likely to show sincerity in writing, counseling, and artistic activities.\nThey should be encouraged to steadily continue activities that give them inspiration while keeping their own pace.",
    id: "Sangat imajinatif dan sangat peka terhadap emosi orang lain.\nMemiliki wawasan menengadah langsung ke dalam emosi perasaan serta keadaan sekeliling temanya. Namun bisa sangat capak jika dipaparkan keramaian bertensi tanpa istirahat panjang dalam kesendirian yang menenangkan.\nBakal bersinar untuk wawasan pendamping sesama, penceritaan, kepengurusan konseling serta pencarian makna kreativitas.\nMengencangkan keberlajutan berinspiratif ini namun menompangkan pecerahan istirahat kendirian yang patuh secara masa bertahap dapat menghindari lesu depresi seumur panjang.",
    ms: "Sangat berimaginasi dan sungguh peka terhadap emosi orang lain.\nMempunyai wawasan kepada kejiwaan seseorang serta mempamerkan kewarasan tafsiran di keadaan meruncing masa kini. Merenggut kejangkulan tenaga jika ketiadaan penyendirin secukup untuk pengembalian fitrah tenaganya.\nPembukaan perbakat akan berpihak ke jurusan pena penulisan bertinta tajam, perkongan nasihat serta kepastian karya seni.\nDorongan merancakkan lagi amalan sedari kecil di mana menonjolkan potensi berseni peribadi dengan mengukur had keupayaan secara bertahap akan mengekangkan kelelahan buat jangka masa tidak ketentuan lamanya nanti.",
    th: "จินตนาการสูงล้ำและค่อนข้างอ่อนไหวกับอารมณ์ของผู้อื่น\nมีวิสัยทัศน์หรือสามารถเข้าใจไปถึงก้นบึ้งของหัวใจคนอื่นและเข้าใจความหมายเบื้องหลังของสถานการณ์ อย่างไรก็ตาม พวกเขาอาจจะเหน็ดเหนื่อยได้ง่ายหากไม่มีเวลาอยู่ลำพังและพักผ่อนเพียงพอ\nมีแนวโน้มสูงที่จะพบทางที่ยอดเยี่ยมในการทำผลงานเขียน การให้คำปรึกษา และกิจกรรมทางศิลปะ\nควรได้รับการสนับสนุนให้พยายามค่อยๆ ทำกิจกรรมที่ให้แรงบันดาลใจด้วยตนเองต่อไปอย่างสม่ำเสมอในขณะที่ยังสามารถรักษาจังหวะของตัวเองเอาไว้"
  },
  infp: {
    en: "Emotionally rich, they quietly and deeply observe their surroundings.\nRich in imagination and creativity, showing sincerity in what they believe. However, they can suffer stress from practical matters.\nThey are highly likely to show deep immersion and inspiration in writing, arts, and creative activities.\nTeaching them how to balance ideals and reality will let them achieve their dreams more healthily.",
    id: "Kaya secara emosional, mereka dengan tenang mengamati sekeliling mereka.\nMenemukan daya cipta kreativitas pada apa yang dipercayai oleh insting dasar imajinasi mereka. Namun tekanan realistik sering mendeprasikan ketahanan persekitaran relasi luar rumahnya.\nMunpuni di masa ke hadapannya andai menyisir persembahan dunia tulis menulis, seni budaya serta kesenangan kegiatan mencabar bakat artistik.\nMemadu kasih antara angan impin ide dengan alam fakta yang merunsingkan harus dicontohkan awal awal bagi menjaga keutuhm kemahiran mereka sejati.",
    ms: "Kaya emosinya, mereka senyap memerhatikan persekitaran mereka dengan mendalam.\nKaya dalam dunia lamunan memanjangkan potensi kekreativitian, menampilkan jujur pertaruhan mereka kepada penjangkaan percaya. Sedih dan risau menyedut penekanan emosinya ke taraf tegang yang mendalam.\nMemperlihatkan keberhasilan mantap di kala penyangkuan dunia karya penulisan bertinta kreatif dan seni kebahasaan.\nPengukir impian harus dipadu kasihkan dengan pengawalan tuntutan realiti sebenar kehidupan awal supaya mereka berjaya menutupi impian masa kecil mereka kelak.",
    th: "พวกเขามีอารมณ์ที่มากมาย รับรู้และสังเกตสิ่งต่างๆ เงียบๆ ได้อย่างดี\nมีพร้อมด้วยทักษะในด้านจินตนาการและความคิดสร้างสรรค์ แสดงความจริงใจต่อสิ่งที่พวกเขาเชื่อมั่น แต่บางทีพวกเขาอาจต้องเผชิญกับความเครียดจากเรื่องจริงที่เกิดขึ้นในชีวิต\nมีแนวโน้มสูงมากที่จะแสดงความสามารถในการเชื่อมโยงและการรับแรงบันดาลใจอย่างลึกซึ้งในผลงานเขียน งานศิลปะ และงานกิจกรรมสร้างสรรค์อื่นๆ\nการชี้แนะถึงวิธีการสร้างสมดุลระหว่างอุดมคติและความเป็นจริงจะช่วยให้พวกเขาบรรลุความฝันเหล่านั้นได้อย่างมีสุขภาพดีมากยิ่งขึ้น"
  }
};

const langs = ['en', 'id', 'ms', 'th'];

langs.forEach(lang => {
  const filePath = path.join('src', 'i18n', 'messages', lang, 'kyk.json');
  if (!fs.existsSync(filePath)) return;
  
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  Object.keys(summaries).forEach(mbti => {
    data.computed[`summary_${mbti}`] = summaries[mbti][lang];
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
